### ISSUE TITLE
Add info about how to call a doorbell (for look out)

### ISSUE THREAD

**Issue by lkadar2015** [TECH7Fox/sip-hass-docs#22]
Hello Jordy,

I would like to connect to my video doorbell from my SIPCard.

I have added the doorbell according to your description: https://tech7fox.github.io/sip-hass-docs/docs/add-on/guides/doorbell

The doorbell is successfully registered in Asterisk.

How can I ask the SIPCard to call number 8000?

The SIPCard is also successfully registered in Asterisk.

I tried adding it to the "custom" list but it is not calling the doorbell and I see no issue in the Asterisk log for that.

It must be trivial, but I cannot find it out.

This is my card config:
```
type: custom:sipjs-card
server: homeassistant.local
port: '8089'
button_size: '48'
state_color: true
auto_answer: false
hide_me: true
custom_title: Xyz
video: true
custom:
  - name: Doorbell
    number: '8000'
    icon: mdi:doorbell-video
dtmfs: []
iceTimeout: 5
prefix: ''
ringtone: /local/asterisk/ringtone.mp3
ringbacktone: /local/asterisk/backtone.mp3
extensions:
  - person: person.xyz
    name: Xyz
    extension: '100'
    secret: ...
    icon: mdi:account

```
